### ISSUE TITLE
System.ArgumentException: Unknown parameter in Content-Disposition. Ask developer to fix! Parameter: INLINE  BOUNDARY

### ISSUE THREAD

**Issue by serprex** [foens/hpop#28]
System.ArgumentException: Unknown parameter in Content-Disposition. Ask developer to fix! Parameter: INLINE  BOUNDARY
   at OpenPop.Mime.Header.HeaderFieldParser.ParseContentDisposition(String headerValue)
   at OpenPop.Mime.Header.MessageHeader.ParseHeader(String headerName, String headerValue)
   at OpenPop.Mime.Header.MessageHeader.ParseHeaders(NameValueCollection headers)
   at OpenPop.Mime.Header.MessageHeader..ctor(NameValueCollection headers)
   at OpenPop.Mime.Header.HeaderExtractor.ExtractHeadersAndBody(Byte[] fullRawMessage, MessageHeader& headers, Byte[]& body)
   at OpenPop.Mime.Message..ctor(Byte[] rawMessageContent, Boolean parseBody)
   at OpenPop.Pop3.Pop3Client.GetMessageHeaders(Int32 messageNumber)

**Comment by foens** [comment]
Seems like a malformed email. Can't fix this in a good way. Thanks for reporting though.
Feel free to reopen if you do not agree with me.
