### ISSUE TITLE
System.ArgumentException: '\"iso-8859-1\"' is not a supported encoding name

### ISSUE THREAD

**Issue by nelero** [foens/hpop#54]
When retrieving a message via GetMessage, sometimes i got
An exception occured : System.ArgumentException: '\"iso-8859-1\"' is not a supported encoding name.
Parameter name : name
at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
at System.Globalization.EncodingTable.GetCodePageFromName(String name)
at OpenPop.Mime.Decode.EncodingFinder.FindEncoding(String characterSet)
at OpenPop.Mime.MessagePart..ctor(Byte[] rawBody, MessageHeader headers, IParsingErrorHandler parsingErrorHandler)
at OpenPop.Mime.MessagePart.ParseMultiPartBody(Byte[] rawBody)
at OpenPop.Mime.MessagePart..ctor(Byte[] rawBody, MessageHeader headers, IParsingErrorHandler parsingErrorHandler)
at OpenPop.Mime.Message..ctor(Byte[] rawMessageContent, Boolean parseBody, IParsingErrorHandler parsingErrorHandler)
at OpenPop.Pop3.Pop3Client.GetMessage(Int32 messageNumber, IParsingErrorHandler parsingErrorHandler)

How can i solve this ?

**Comment by jjhii** [comment]
In the me too:

Is there a way of adding encodings?

System.ArgumentException: 'csISO4UnitedKingdom' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at OpenPop.Mime.Decode.EncodingFinder.FindEncoding(String characterSet)
   at OpenPop.Mime.MessagePart.ParseBodyEncoding(String characterSet)
   at OpenPop.Mime.MessagePart..ctor(Byte[] rawBody, MessageHeader headers, IParsingErrorHandler parsingErrorHandler)
   at OpenPop.Pop3.Pop3Client.GetMessage(Int32 messageNumber, IParsingErrorHandler parsingErrorHandler)

**Comment by qadeemakhtar** [comment]
Hi @jjhii  @nelero  I am also getting the Same Exception on GetMessage  Can any Help Please.

**Comment by foens** [comment]
You can use the EncodingFinder. See http://hpop.sourceforge.net/exampleChangeCharacterSetMapping.php for examples.
