### ISSUE TITLE
embedded PDF linked to iCloud file

### ISSUE THREAD

**Issue by fuzeckunkel** [foens/hpop#74]
10/30/2018 4:55:54 PM DEBUG: Connect-Response: "+OK Hello there."
10/30/2018 4:55:54 PM DEBUG: SendCommand: "USER ACA_reimbursements_aaa-alliedgroup@fuzeqna.com"
10/30/2018 4:55:54 PM DEBUG: Server-Response: "+OK Password required."
10/30/2018 4:55:54 PM DEBUG: SendCommand: "PASS @@@help"
10/30/2018 4:55:54 PM DEBUG: Server-Response: "+OK logged in."
10/30/2018 4:55:54 PM DEBUG: SendCommand: "STAT"
10/30/2018 4:55:54 PM DEBUG: Server-Response: "+OK 1 143940"
10/30/2018 4:55:54 PM DEBUG: SendCommand: "RETR 1"
10/30/2018 4:55:54 PM DEBUG: Server-Response: "+OK 143940 octets follow."
10/30/2018 4:55:55 PM TestForm: Message fetching failed: Unknown parameter in Content-Disposition. Ask developer to fix! Parameter: REMOTE-IMAGE
Stack trace:
   at OpenPop.Mime.Header.HeaderFieldParser.ParseContentDisposition(String headerValue) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\Header\HeaderFieldParser.cs:line 240
   at OpenPop.Mime.Header.MessageHeader.ParseHeader(String headerName, String headerValue) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\Header\MessageHeader.cs:line 452
   at OpenPop.Mime.Header.MessageHeader.ParseHeaders(NameValueCollection headers) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\Header\MessageHeader.cs:line 306
   at OpenPop.Mime.Header.MessageHeader..ctor(NameValueCollection headers, IParsingErrorHandler parsingErrorHandler) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\Header\MessageHeader.cs:line 270
   at OpenPop.Mime.Header.HeaderExtractor.ExtractHeadersAndBody(Byte[] fullRawMessage, MessageHeader& headers, Byte[]& body, IParsingErrorHandler parsingErrorHandler) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\Header\HeaderExtractor.cs:line 72
   at OpenPop.Mime.MessagePart.GetMessagePart(Byte[] rawMessageContent) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\MessagePart.cs:line 348
   at OpenPop.Mime.MessagePart.ParseMultiPartBody(Byte[] rawBody) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\MessagePart.cs:line 332
   at OpenPop.Mime.MessagePart.ParseBody(Byte[] rawBody) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\MessagePart.cs:line 303
   at OpenPop.Mime.MessagePart..ctor(Byte[] rawBody, MessageHeader headers, IParsingErrorHandler parsingErrorHandler) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\MessagePart.cs:line 248
   at OpenPop.Mime.MessagePart.GetMessagePart(Byte[] rawMessageContent) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\MessagePart.cs:line 351
   at OpenPop.Mime.MessagePart.ParseMultiPartBody(Byte[] rawBody) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\MessagePart.cs:line 332
   at OpenPop.Mime.MessagePart.ParseBody(Byte[] rawBody) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\MessagePart.cs:line 303
   at OpenPop.Mime.MessagePart..ctor(Byte[] rawBody, MessageHeader headers, IParsingErrorHandler parsingErrorHandler) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\MessagePart.cs:line 248
   at OpenPop.Mime.Message..ctor(Byte[] rawMessageContent, Boolean parseBody, IParsingErrorHandler parsingErrorHandler) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\Message.cs:line 95
   at OpenPop.Mime.Message..ctor(Byte[] rawMessageContent, IParsingErrorHandler parsingErrorHandler) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Mime\Message.cs:line 63
   at OpenPop.Pop3.Pop3Client.GetMessage(Int32 messageNumber, IParsingErrorHandler parsingErrorHandler) in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPop\Pop3\Pop3Client.cs:line 726
   at OpenPop.TestApplication.TestForm.ReceiveMails() in C:\Users\ckunkel\Documents\Visual Studio 2015\Projects\Fuze80Sln\OpenPopTest\TestForm.cs:line 505

**Comment by jstedfast** [comment]
Unfortunately OpenPOP is too strict and fails when it encounters parameter tags that it does not know about such as, in this case, `remote-image`.

Anyone else hitting this problem is invited to try out [MailKit](https://github.com/jstedfast/MailKit) instead which does not have this problem.

**Comment by mkucera1** [comment]
Bump!  Just received this same message for the first time. 

Excerpt from header:

--Apple-Mail-1F1E9A23-9E4C-4F34-A7CA-29F4E9B0D7D4
Content-Type: image/jpeg;
	name=IMG_0840.JPG;
	x-apple-part-url=772927D6-893D-4249-85E4-88CDFEC5E6A3
Content-Disposition: inline;
	**remote-image=IMG_0840.JPG;**
	filename=IMG_0840.JPG
Content-Transfer-Encoding: base64
Content-Id: <772927D6-893D-4249-85E4-88CDFEC5E6A3>

/9j/4Qf0RXhpZgAATU0AKgAAAAgACwEPAAIAAAAGAAAAkgEQAAIAAAAPAAAAmAESAAMAAAABAAYA
AAEaAAUAAAABAAAAqAEbAAUAAAABAAAAsAEoAAMAAAABAAIAAAExAAIAAAAEOS4xAAEyAAIAAAAU

**Comment by jstedfast** [comment]
@mkucera1 Give MailKit a try. I think OpenPOP is an abandoned project.
